on:
  push:
    branches:
      - 'main'

name: Publish on Netlify
jobs:
  publish:
    environment: 'Netlify Deploy Prod'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: sources

    - uses: roman-kashitsyn/mmapped.blog/.github/workflows/render-site.yml@main
      with:
        source_dir: sources
        output_dir: site

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
