on:
  push:
    branches:
      - 'main'

name: Publish on Netlify
jobs:
  publish:
    environment: 'Netlify Deploy'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: sources

    - uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.3'

    - name: Cache Racket dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/racket
          ~/.local/share/racket
        key: ${{ runner.os }}-racket-8.5

    - run: raco pkg install --auto --skip-installed "git+https://git.sr.ht/~mbutterick/pollen"
    - run: raco pollen render sources
    - run: raco pollen publish sources site 
    - run: rm site/template.html site/README.md site/Dockerfile

    - name: Publish
      uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
