on:
  workflow_call:
    inputs:
      source_dir:
        required: true
        type: string
      output_dir:
        required: true
        type: string

name: Render website from source
job:
  render_site:
    runs-on: ubuntu-latest

    steps:
    - uses: Bogdanp/setup-racket@v1.7
      with:
        architecture: 'x64'
        distribution: 'full'
        variant: 'CS'
        version: '8.3'

    - name: Cache Racket dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/racket
          ~/.local/share/racket
        key: ${{ runner.os }}-racket-8.3

    - run: raco pkg install --auto --skip-installed pollen
    - run: raco pollen render ${{inputs.input_dir}}
    - run: raco pollen publish ${{inputs.input_dir}} ${{inputs.output_dir}} 
    - run: rm -f ${{inputs.output_dir}}/template.html ${{inputs.output_dir}}/README.md ${{inputs.output_dir}}/Dockerfile
